#!/bin/bash

set -e
set -u

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_MASTER" <<-EOSQL
DO
\$\$
BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$WORKSHOP_POSTGRES_USER') THEN
                CREATE ROLE $WORKSHOP_POSTGRES_USER LOGIN PASSWORD '$WORKSHOP_POSTGRES_PASSWORD';
        END IF;
END
\$\$;

SELECT 'CREATE DATABASE $WORKSHOP_POSTGRES_DB OWNER $WORKSHOP_POSTGRES_USER'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$WORKSHOP_POSTGRES_DB')
\gexec

GRANT ALL PRIVILEGES ON DATABASE $WORKSHOP_POSTGRES_DB TO $WORKSHOP_POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=1 -U "$WORKSHOP_POSTGRES_USER" -d "$WORKSHOP_POSTGRES_DB" <<-EOSQL
CREATE TABLE IF NOT EXISTS books (
         id SERIAL PRIMARY KEY,
         title VARCHAR(255) NOT NULL,
         author VARCHAR(255) NOT NULL,
         description TEXT NOT NULL
);
EOSQL